azs:
- name: z1
  cloud_properties:
    datacenters:
    - clusters: [((vcenter_cluster)): {}]
- name: z2
  cloud_properties:
    datacenters:
    - clusters: [((vcenter_cluster)): {}]
- name: z3
  cloud_properties:
    datacenters:
    - clusters: [((vcenter_cluster)): {}]

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 3240
- name: large
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 30_240

disk_types:
- name: default
  disk_size: 3000
- name: large
  disk_size: 50_000

networks:
- name: public
  type: vip
  subnets:
  - cloud_properties:
      name: ((external_network_name))
    dns: [((external_dns))]
    gateway: ((external_gw))
    reserved: [((external_reserved_ips))]
    az: z1
    range: ((external_cidr))
    static: [((external_static_ips))]

- name: default
  type: manual
  subnets:
  - range: ((internal_cidr))
    reserved: [((internal_reserved_ips))]
    az: z1
    gateway: ((internal_gw))
    dns: [((internal_dns))]
    cloud_properties:
      name: ((network_name))
    static: [((internal_static_ips))]

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: default
